<a href="https://colab.research.google.com/github/charithrd/Python-E-Learning/blob/main/LeadTime.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

> # <font color=#2B65EC>**1. Data Pre-processing and Cleaning**</font>

> # <font color='lightblue'>Importing required libraries</font>

- pandas and numpy libraries are particularly selected for data analysis and manipulation.
- In addition from pandas library series and dataframe classes are imported.
- Series assist in holding one dimensional labelled arrays and DataFrame help to handle tabular two dimensional dataset.

In [31]:
import pandas as pd
from pandas import Series,DataFrame
import numpy as np

> ## <font color='lightblue'>Importing glob module to assist in finding file paths matching a specified pattern</font>

- glob function within glob module is used to search for '/content/K+N Seafreight WK*.xlsm' pattern within the content directory and return all the matching files.

In [32]:
import glob
glob.glob('/content/K+N Seafreight WK*.xlsm')

['/content/K+N Seafreight WK 11.xlsm',
 '/content/K+N Seafreight WK 03.xlsm',
 '/content/K+N Seafreight WK 09.xlsm',
 '/content/K+N Seafreight WK 01.xlsm',
 '/content/K+N Seafreight WK 13.xlsm',
 '/content/K+N Seafreight WK 05.xlsm',
 '/content/K+N Seafreight WK 07.xlsm']

> ### <font color='lightblue'>Initialising an Empty List and Append Files</font>
- An empty list is created using 'comb_dfs = []'
- For loop iterates over each file path that matches the glob function pattern and assign each file name to the variable 'one_filename'.
- Pandas read_excel function is used to read the files in 'one_filename' and load into a dataframe. This dataframe is then assigned to the 'new_df' variable.
- Finally, 'new_df' dataframe is added to the 'comb_dfs' list.

In [33]:
comb_dfs = []
for one_filename in glob.glob('/content/K+N Seafreight WK*.xlsm'):
    print(f'loading {one_filename}')
    new_df = pd.read_excel(one_filename)
    comb_dfs.append(new_df)

loading /content/K+N Seafreight WK 11.xlsm
loading /content/K+N Seafreight WK 03.xlsm
loading /content/K+N Seafreight WK 09.xlsm
loading /content/K+N Seafreight WK 01.xlsm
loading /content/K+N Seafreight WK 13.xlsm
loading /content/K+N Seafreight WK 05.xlsm
loading /content/K+N Seafreight WK 07.xlsm

In [34]:
# Pandas concatenate function is used to combine multiple dataframes within 'comb_dfs'
df =pd.concat(comb_dfs)

> ### <font color='lightblue'>List comprehension using LLM's</font>

- Code that we used to Initialise an empty list and appendthe files to a dataframe is optimised using List Comprehension technique.
- To achieve this objective we have seeked recomendations from LLM.
- Similar output is achieved with minimal coding.

In [35]:
df = pd.concat([pd.read_excel(one_filename)
      for one_filename in glob.glob('/content/K+N Seafreight WK*.xlsm')
      if not print(f'loading {one_filename}')
])

loading /content/K+N Seafreight WK 11.xlsm
loading /content/K+N Seafreight WK 03.xlsm
loading /content/K+N Seafreight WK 09.xlsm
loading /content/K+N Seafreight WK 01.xlsm
loading /content/K+N Seafreight WK 13.xlsm
loading /content/K+N Seafreight WK 05.xlsm
loading /content/K+N Seafreight WK 07.xlsm

In [36]:
# Dimensions of the dataframe using shape function.
df.shape

(771, 33)

In [37]:
# First 15 rows of the dataframe is retrieved using head() function.
df.head(15)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32
0,File Reference,Voyage Number,Container No,Cont Type,Port of Loading,Port of Arrival,Carrier,FAK Y/N?,Ocean Freight USD,Hazardous,...,Port Inf,Energy Adjustment and Fuel Duty Recovery GBP,Gen Set,HAZ Surcharge,Rework,GBP Total,Gate In (Freight),Delivery Month,USD Invoice Number,GBP Invoice Number
1,1057778900,SFEL0VAHFW1MABD,BEAU4774152,41,CGP,FXT,CMDU,NAC,1165,0,...,6,30,NaN,0,NaN,1140.94,2,4,GB14297206,GB14297204
2,1057778900,SFEL0VAHFW1MABD,BEAU4783658,41,CGP,FXT,CMDU,NAC,1165,0,...,6,30,NaN,0,NaN,1018.05,2,4,GB14297206,GB14297204
3,1057778900,SFEL0VAHFW1MABD,BEAU6133076,41,CGP,FXT,CMDU,NAC,1165,0,...,6,30,NaN,0,NaN,1018.05,2,4,GB14297206,GB14297204
4,1057778900,SFEL0VAHFW1MABD,BMOU6711230,41,CGP,FXT,CMDU,NAC,1165,0,...,6,30,NaN,0,NaN,1018.05,2,4,GB14297206,GB14297204
5,1057778900,SFEL0VAHFW1MABD,CAIU7615056,41,CGP,FXT,CMDU,NAC,1165,0,...,6,30,NaN,0,NaN,1018.05,2,4,GB14297206,GB14297204
6,1057778900,SFEL0VAHFW1MABD,CMAU6448825,41,CGP,FXT,CMDU,NAC,1165,0,...,6,30,NaN,0,NaN,1018.05,2,4,GB14297206,GB14297204
7,1057778900,SFEL0VAHFW1MABD,CMAU7009745,41,CGP,FXT,CMDU,NAC,1165,0,...,6,30,NaN,0,NaN,1018.05,2,4,GB14297206,GB14297204
8,1057778900,SFEL0VAHFW1MABD,CMAU7116804,41,CGP,FXT,CMDU,NAC,1165,0,...,6,30,NaN,0,NaN,1018.05,2,4,GB14297206,GB14297204
9,1057778900,SFEL0VAHFW1MABD,GESU6897873,41,CGP,FXT,CMDU,NAC,1165,0,...,6,30,NaN,0,NaN,1018.05,2,4,GB14297206,GB14297204
10,1057498406,SFEL0VAHFW1MAK,BEAU6131896,41,YTN,FXT,CMDU,NAC,920,0,...,6,30,NaN,0,NaN,1088.05,3,4,GB14298599,GB14298600
11,1057498406,SFEL0VAHFW1MAK,CMAU5464251,41,YTN,FXT,CMDU,NAC,920,0,...,6,30,NaN,0,NaN,1018.05,3,4,GB14298599,GB14298600
12,1057498406,SFEL0VAHFW1MAK,CMAU6772990,41,YTN,FXT,CMDU,NAC,920,0,...,6,30,NaN,0,NaN,1070.94,3,4,GB14298599,GB14298600
13,1057498406,SFEL0VAHFW1MAK,GESU6934175,41,YTN,FXT,CMDU,NAC,920,0,...,6,30,NaN,0,NaN,1018.05,3,4,GB14298599,GB14298600
14,1057367239,SFIEFW408WKH,MSCU5143926,41,KOS,FXT,MSCU,NAC,1320,0,...,6,30,NaN,0,NaN,1088.05,2,4,GB14298604,GB14298603

### Observations
- With the head function output we can observe that the dataset headers exist in row 1 (index 0)
- Hence, we are using iloc function to target row 1 'iloc[0]' as headers and subsequently drop row 1 since it's the new header.

In [38]:
# Set the first row as the header.
df.columns = df.iloc[0]

# Drop the first row since it's now the header.
df_trim = df.drop(0).reset_index(drop=True)

# Display the DataFrame to confirm the changes.
df_trim.head(15)

,File Reference,Voyage Number,Container No,Cont Type,Port of Loading,Port of Arrival,Carrier,FAK Y/N?,Ocean Freight USD,Hazardous,...,Port Inf,Energy Adjustment and Fuel Duty Recovery GBP,Gen Set,HAZ Surcharge,Rework,GBP Total,Gate In (Freight),Delivery Month,USD Invoice Number,GBP Invoice Number
0,1057778900,SFEL0VAHFW1MABD,BEAU4774152,41,CGP,FXT,CMDU,NAC,1165,0,...,6,30,NaN,0,NaN,1140.94,2,4,GB14297206,GB14297204
1,1057778900,SFEL0VAHFW1MABD,BEAU4783658,41,CGP,FXT,CMDU,NAC,1165,0,...,6,30,NaN,0,NaN,1018.05,2,4,GB14297206,GB14297204
2,1057778900,SFEL0VAHFW1MABD,BEAU6133076,41,CGP,FXT,CMDU,NAC,1165,0,...,6,30,NaN,0,NaN,1018.05,2,4,GB14297206,GB14297204
3,1057778900,SFEL0VAHFW1MABD,BMOU6711230,41,CGP,FXT,CMDU,NAC,1165,0,...,6,30,NaN,0,NaN,1018.05,2,4,GB14297206,GB14297204
4,1057778900,SFEL0VAHFW1MABD,CAIU7615056,41,CGP,FXT,CMDU,NAC,1165,0,...,6,30,NaN,0,NaN,1018.05,2,4,GB14297206,GB14297204
5,1057778900,SFEL0VAHFW1MABD,CMAU6448825,41,CGP,FXT,CMDU,NAC,1165,0,...,6,30,NaN,0,NaN,1018.05,2,4,GB14297206,GB14297204
6,1057778900,SFEL0VAHFW1MABD,CMAU7009745,41,CGP,FXT,CMDU,NAC,1165,0,...,6,30,NaN,0,NaN,1018.05,2,4,GB14297206,GB14297204
7,1057778900,SFEL0VAHFW1MABD,CMAU7116804,41,CGP,FXT,CMDU,NAC,1165,0,...,6,30,NaN,0,NaN,1018.05,2,4,GB14297206,GB14297204
8,1057778900,SFEL0VAHFW1MABD,GESU6897873,41,CGP,FXT,CMDU,NAC,1165,0,...,6,30,NaN,0,NaN,1018.05,2,4,GB14297206,GB14297204
9,1057498406,SFEL0VAHFW1MAK,BEAU6131896,41,YTN,FXT,CMDU,NAC,920,0,...,6,30,NaN,0,NaN,1088.05,3,4,GB14298599,GB14298600
10,1057498406,SFEL0VAHFW1MAK,CMAU5464251,41,YTN,FXT,CMDU,NAC,920,0,...,6,30,NaN,0,NaN,1018.05,3,4,GB14298599,GB14298600
11,1057498406,SFEL0VAHFW1MAK,CMAU6772990,41,YTN,FXT,CMDU,NAC,920,0,...,6,30,NaN,0,NaN,1070.94,3,4,GB14298599,GB14298600
12,1057498406,SFEL0VAHFW1MAK,GESU6934175,41,YTN,FXT,CMDU,NAC,920,0,...,6,30,NaN,0,NaN,1018.05,3,4,GB14298599,GB14298600
13,1057367239,SFIEFW408WKH,MSCU5143926,41,KOS,FXT,MSCU,NAC,1320,0,...,6,30,NaN,0,NaN,1088.05,2,4,GB14298604,GB14298603
14,1057367239,SFIEFW408WKH,MSDU4268007,40,KOS,FXT,MSCU,NAC,1320,0,...,6,30,NaN,0,NaN,1018.05,2,4,GB14298604,GB14298603

In [39]:
# Returning the data types of each column in 'df_trim' DataFrame.
df_trim.dtypes

0
File Reference                                  object
Voyage Number                                   object
Container No                                    object
 Cont Type                                      object
Port of Loading                                 object
Port of Arrival                                 object
Carrier                                         object
FAK Y/N?                                        object
 Ocean Freight USD                              object
Hazardous                                       object
Reefer                                          object
 ISPS USD                                       object
 ENS Fee                                        object
Sulphur Chg                                     object
GOH Surcharge                                   object
USD Total                                       object
No of Drops                                     object
 Terminal Handling GBP                          object
 Port Security GBP                              object
 Documents GBP                                  object
 Customs Clearance GBP                          object
 Haulage GBP                                    object
DRS                                             object
 Port Inf                                       object
Energy Adjustment and Fuel Duty Recovery GBP    object
Gen Set                                         object
HAZ Surcharge                                   object
Rework                                          object
GBP Total                                       object
Gate In (Freight)                               object
Delivery Month                                  object
USD Invoice Number                              object
GBP Invoice Number                              object
dtype: object

### Observations
- At a glance we can spot that data in each column is created as an object.
- With the head() function we have noticed that columns like 'Ocean Freight USD' are numerical columns.
- Hence, the numerical columns within this dataset need converting to data type 'int' or 'floats' where necessary.

In [40]:
# Before converting numerical columns, we first check for any extra spaces or inconsistencies in the column names.
print(df_trim.columns)

Index(['File Reference', 'Voyage Number', 'Container No', ' Cont Type ',
       'Port of Loading', 'Port of Arrival', 'Carrier', 'FAK Y/N?',
       ' Ocean Freight USD', 'Hazardous', 'Reefer', ' ISPS USD ', ' ENS Fee ',
       'Sulphur Chg', 'GOH Surcharge', 'USD Total', 'No of Drops',
       ' Terminal Handling GBP ', ' Port Security GBP ', ' Documents GBP ',
       ' Customs Clearance GBP ', ' Haulage GBP ', 'DRS', ' Port Inf ',
       'Energy Adjustment and Fuel Duty Recovery GBP', 'Gen Set',
       'HAZ Surcharge', 'Rework', 'GBP Total', 'Gate In (Freight)',
       'Delivery Month', 'USD Invoice Number', 'GBP Invoice Number'],
      dtype='object', name=0)

- It is visible that certain columns such as ' ENS Fee ' has leading and trailing whitespaces and some columns such as ' Ocean Freight USD' has only leading whitespace.

- To eliminate the inconsistency and clean the whitespace we are using strip() function.

In [41]:
# Remove any leading/trailing whitespace from column names and printing the refined column names.
df_trim.columns = df_trim.columns.str.strip()
print(df_trim.columns)

Index(['File Reference', 'Voyage Number', 'Container No', 'Cont Type',
       'Port of Loading', 'Port of Arrival', 'Carrier', 'FAK Y/N?',
       'Ocean Freight USD', 'Hazardous', 'Reefer', 'ISPS USD', 'ENS Fee',
       'Sulphur Chg', 'GOH Surcharge', 'USD Total', 'No of Drops',
       'Terminal Handling GBP', 'Port Security GBP', 'Documents GBP',
       'Customs Clearance GBP', 'Haulage GBP', 'DRS', 'Port Inf',
       'Energy Adjustment and Fuel Duty Recovery GBP', 'Gen Set',
       'HAZ Surcharge', 'Rework', 'GBP Total', 'Gate In (Freight)',
       'Delivery Month', 'USD Invoice Number', 'GBP Invoice Number'],
      dtype='object', name=0)

In [42]:
# Converting the columns datatype as necessary, while replacing null values with zero.
df_trim['Ocean Freight USD'] = pd.to_numeric(df_trim['Ocean Freight USD'], errors='coerce').fillna(0).astype(float)
df_trim['Hazardous'] = pd.to_numeric(df_trim['Hazardous'], errors='coerce').fillna(0).astype(float)
df_trim['Reefer'] = pd.to_numeric(df_trim['Reefer'], errors='coerce').fillna(0).astype(float)
df_trim['ISPS USD'] = pd.to_numeric(df_trim['ISPS USD'], errors='coerce').fillna(0).astype(float)
df_trim['ENS Fee'] = pd.to_numeric(df_trim['ENS Fee'], errors='coerce').fillna(0).astype(float)
df_trim['Sulphur Chg'] = pd.to_numeric(df_trim['Sulphur Chg'], errors='coerce').fillna(0).astype(float)
df_trim['GOH Surcharge'] = pd.to_numeric(df_trim['GOH Surcharge'], errors='coerce').fillna(0).astype(float)
df_trim['USD Total'] = pd.to_numeric(df_trim['USD Total'], errors='coerce').fillna(0).astype(float)
df_trim['No of Drops'] = pd.to_numeric(df_trim['No of Drops'], errors='coerce').fillna(0).astype(int)
df_trim['Terminal Handling GBP'] = pd.to_numeric(df_trim['Terminal Handling GBP'], errors='coerce').fillna(0).astype(float)
df_trim['Port Security GBP'] = pd.to_numeric(df_trim['Port Security GBP'], errors='coerce').fillna(0).astype(float)
df_trim['Documents GBP'] = pd.to_numeric(df_trim['Documents GBP'], errors='coerce').fillna(0).astype(float)
df_trim['Customs Clearance GBP'] = pd.to_numeric(df_trim['Customs Clearance GBP'], errors='coerce').fillna(0).astype(float)
df_trim['Haulage GBP'] = pd.to_numeric(df_trim['Haulage GBP'], errors='coerce').fillna(0).astype(float)
df_trim['DRS'] = pd.to_numeric(df_trim['DRS'], errors='coerce').fillna(0).astype(float)
df_trim['Port Inf'] = pd.to_numeric(df_trim['Port Inf'], errors='coerce').fillna(0).astype(float)
df_trim['Energy Adjustment and Fuel Duty Recovery GBP'] = pd.to_numeric(df_trim['Energy Adjustment and Fuel Duty Recovery GBP'], errors='coerce').fillna(0).astype(float)
df_trim['Gen Set'] = pd.to_numeric(df_trim['Gen Set'], errors='coerce').fillna(0).astype(float)
df_trim['HAZ Surcharge'] = pd.to_numeric(df_trim['HAZ Surcharge'], errors='coerce').fillna(0).astype(float)
df_trim['Rework'] = pd.to_numeric(df_trim['Rework'], errors='coerce').fillna(0).astype(float)
df_trim['GBP Total'] = pd.to_numeric(df_trim['GBP Total'], errors='coerce').fillna(0).astype(float)
df_trim['Gate In (Freight)'] = pd.to_numeric(df_trim['Gate In (Freight)'], errors='coerce').fillna(0).astype(int)
df_trim['Delivery Month'] = pd.to_numeric(df_trim['Delivery Month'], errors='coerce').fillna(0).astype(int)

In [43]:
# Dropping not required columns from the dataframe.
df_trim.drop(['File Reference','FAK Y/N?'],axis=1,inplace=True)

In [44]:
# Checking the amended data types and trimmed columns.
df_trim.dtypes

0
Voyage Number                                    object
Container No                                     object
Cont Type                                        object
Port of Loading                                  object
Port of Arrival                                  object
Carrier                                          object
Ocean Freight USD                               float64
Hazardous                                       float64
Reefer                                          float64
ISPS USD                                        float64
ENS Fee                                         float64
Sulphur Chg                                     float64
GOH Surcharge                                   float64
USD Total                                       float64
No of Drops                                       int64
Terminal Handling GBP                           float64
Port Security GBP                               float64
Documents GBP                                   float64
Customs Clearance GBP                           float64
Haulage GBP                                     float64
DRS                                             float64
Port Inf                                        float64
Energy Adjustment and Fuel Duty Recovery GBP    float64
Gen Set                                         float64
HAZ Surcharge                                   float64
Rework                                          float64
GBP Total                                       float64
Gate In (Freight)                                 int64
Delivery Month                                    int64
USD Invoice Number                               object
GBP Invoice Number                               object
dtype: object

In [45]:
# verifying the cleaned dataset.
df_trim.head(15)

,Voyage Number,Container No,Cont Type,Port of Loading,Port of Arrival,Carrier,Ocean Freight USD,Hazardous,Reefer,ISPS USD,...,Port Inf,Energy Adjustment and Fuel Duty Recovery GBP,Gen Set,HAZ Surcharge,Rework,GBP Total,Gate In (Freight),Delivery Month,USD Invoice Number,GBP Invoice Number
0,SFEL0VAHFW1MABD,BEAU4774152,41,CGP,FXT,CMDU,1165.0,0.0,0.0,7.5,...,6.0,30.0,0.0,0.0,0.0,1140.94,2,4,GB14297206,GB14297204
1,SFEL0VAHFW1MABD,BEAU4783658,41,CGP,FXT,CMDU,1165.0,0.0,0.0,7.5,...,6.0,30.0,0.0,0.0,0.0,1018.05,2,4,GB14297206,GB14297204
2,SFEL0VAHFW1MABD,BEAU6133076,41,CGP,FXT,CMDU,1165.0,0.0,0.0,7.5,...,6.0,30.0,0.0,0.0,0.0,1018.05,2,4,GB14297206,GB14297204
3,SFEL0VAHFW1MABD,BMOU6711230,41,CGP,FXT,CMDU,1165.0,0.0,0.0,7.5,...,6.0,30.0,0.0,0.0,0.0,1018.05,2,4,GB14297206,GB14297204
4,SFEL0VAHFW1MABD,CAIU7615056,41,CGP,FXT,CMDU,1165.0,0.0,0.0,7.5,...,6.0,30.0,0.0,0.0,0.0,1018.05,2,4,GB14297206,GB14297204
5,SFEL0VAHFW1MABD,CMAU6448825,41,CGP,FXT,CMDU,1165.0,0.0,0.0,7.5,...,6.0,30.0,0.0,0.0,0.0,1018.05,2,4,GB14297206,GB14297204
6,SFEL0VAHFW1MABD,CMAU7009745,41,CGP,FXT,CMDU,1165.0,0.0,0.0,7.5,...,6.0,30.0,0.0,0.0,0.0,1018.05,2,4,GB14297206,GB14297204
7,SFEL0VAHFW1MABD,CMAU7116804,41,CGP,FXT,CMDU,1165.0,0.0,0.0,7.5,...,6.0,30.0,0.0,0.0,0.0,1018.05,2,4,GB14297206,GB14297204
8,SFEL0VAHFW1MABD,GESU6897873,41,CGP,FXT,CMDU,1165.0,0.0,0.0,7.5,...,6.0,30.0,0.0,0.0,0.0,1018.05,2,4,GB14297206,GB14297204
9,SFEL0VAHFW1MAK,BEAU6131896,41,YTN,FXT,CMDU,920.0,0.0,0.0,7.5,...,6.0,30.0,0.0,0.0,0.0,1088.05,3,4,GB14298599,GB14298600
10,SFEL0VAHFW1MAK,CMAU5464251,41,YTN,FXT,CMDU,920.0,0.0,0.0,7.5,...,6.0,30.0,0.0,0.0,0.0,1018.05,3,4,GB14298599,GB14298600
11,SFEL0VAHFW1MAK,CMAU6772990,41,YTN,FXT,CMDU,920.0,0.0,0.0,7.5,...,6.0,30.0,0.0,0.0,0.0,1070.94,3,4,GB14298599,GB14298600
12,SFEL0VAHFW1MAK,GESU6934175,41,YTN,FXT,CMDU,920.0,0.0,0.0,7.5,...,6.0,30.0,0.0,0.0,0.0,1018.05,3,4,GB14298599,GB14298600
13,SFIEFW408WKH,MSCU5143926,41,KOS,FXT,MSCU,1320.0,0.0,0.0,7.5,...,6.0,30.0,0.0,0.0,0.0,1088.05,2,4,GB14298604,GB14298603
14,SFIEFW408WKH,MSDU4268007,40,KOS,FXT,MSCU,1320.0,0.0,0.0,7.5,...,6.0,30.0,0.0,0.0,0.0,1018.05,2,4,GB14298604,GB14298603