<a href="https://colab.research.google.com/github/charithrd/Python-E-Learning/blob/main/LeadTime.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

> # <font color='lightblue'>Importing required libraries</font>

- pandas and numpy libraries are particularly selected for data analysis and manipulation.
- In addition from pandas library series and dataframe classes are imported.
- Series assist in holding one dimensional labelled arrays and DataFrame help to handle tabular two dimensional dataset.

In [ ]:
import pandas as pd
from pandas import Series,DataFrame
import numpy as np

> ## <font color='lightblue'>Importing glob module to assist in finding file paths matching a specified pattern</font>

- glob function within glob module is used to search for '/content/K+N Seafreight WK*.xlsm' pattern within the content directory and return all the matching files.

In [ ]:
import glob
glob.glob('/content/K+N Seafreight WK*.xlsm')

['/content/K+N Seafreight WK 13.xlsm',
 '/content/K+N Seafreight WK 01.xlsm',
 '/content/K+N Seafreight WK 09.xlsm',
 '/content/K+N Seafreight WK 05.xlsm',
 '/content/K+N Seafreight WK 11.xlsm',
 '/content/K+N Seafreight WK 03.xlsm',
 '/content/K+N Seafreight WK 07.xlsm']

> ### <font color='lightblue'>Initialising an Empty List and Append Files</font>
- An empty list is created using 'comb_dfs = []'
- For loop iterates over each file path that matches the glob function pattern and assign each file name to the variable 'one_filename'.
- Pandas read_excel function is used to read the files in 'one_filename' and load into a dataframe. This dataframe is then assigned to the 'new_df' variable.
- Finally, 'new_df' dataframe is added to the 'comb_dfs' list.

In [ ]:
comb_dfs = []
for one_filename in glob.glob('/content/K+N Seafreight WK*.xlsm'):
    print(f'loading {one_filename}')
    new_df = pd.read_excel(one_filename)
    comb_dfs.append(new_df)

loading /content/K+N Seafreight WK 13.xlsm
loading /content/K+N Seafreight WK 01.xlsm
loading /content/K+N Seafreight WK 09.xlsm
loading /content/K+N Seafreight WK 05.xlsm
loading /content/K+N Seafreight WK 11.xlsm
loading /content/K+N Seafreight WK 03.xlsm
loading /content/K+N Seafreight WK 07.xlsm

In [ ]:
df =pd.concat(comb_dfs)

In [ ]:
df.shape

(771, 33)

In [ ]:
comb_dfs = pd.concat([pd.read_excel(one_filename)
      for one_filename in glob.glob('/content/K+N Seafreight WK*.xlsm')
      if not print(f'loading {one_filename}')
])

loading /content/K+N Seafreight WK 13.xlsm
loading /content/K+N Seafreight WK 01.xlsm
loading /content/K+N Seafreight WK 09.xlsm
loading /content/K+N Seafreight WK 05.xlsm
loading /content/K+N Seafreight WK 11.xlsm
loading /content/K+N Seafreight WK 03.xlsm
loading /content/K+N Seafreight WK 07.xlsm

In [ ]:
df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32
0,File Reference,Voyage Number,Container No,Cont Type,Port of Loading,Port of Arrival,Carrier,FAK Y/N?,Ocean Freight USD,Hazardous,...,Port Inf,Energy Adjustment and Fuel Duty Recovery GBP,Gen Set,HAZ Surcharge,Rework,GBP Total,Gate In (Freight),Delivery Month,USD Invoice Number,GBP Invoice Number
1,1057649316,SBRZ024WK,HLXU5399868,40,NGB,SOU,HLCU,NAC,3234,0,...,17,25,NaN,0,NaN,1098.05,3,5,GB14306197,GB14306199
2,1057997254,SBRZ024WK,BEAU4164843,41,SHA,SOU,HLCU,NAC,3234,0,...,17,25,NaN,0,NaN,1150.94,3,5,GB14306197,GB14306199
3,1058045501,SBRZ024WK,UACU8468865,40,NGB,SOU,HLCU,NAC,3234,0,...,17,25,NaN,0,NaN,1150.94,3,5,GB14306197,GB14306199
4,1058081238,SBRZ024WK,HAMU1606105,41,YTN,SOU,HLCU,NAC,3234,0,...,17,25,NaN,0,NaN,1150.94,3,5,GB14306197,GB14306199

In [ ]:
# Set the first row as the header
df.columns = df.iloc[0]

# Drop the first row since it's now the header
df = df.drop(0).reset_index(drop=True)

# Display the DataFrame to confirm the changes
df.head(15)

,File Reference,Voyage Number,Container No,Cont Type,Port of Loading,Port of Arrival,Carrier,FAK Y/N?,Ocean Freight USD,Hazardous,...,Port Inf,Energy Adjustment and Fuel Duty Recovery GBP,Gen Set,HAZ Surcharge,Rework,GBP Total,Gate In (Freight),Delivery Month,USD Invoice Number,GBP Invoice Number
0,1057649316,SBRZ024WK,HLXU5399868,40,NGB,SOU,HLCU,NAC,3234,0,...,17,25,NaN,0,NaN,1098.05,3,5,GB14306197,GB14306199
1,1057997254,SBRZ024WK,BEAU4164843,41,SHA,SOU,HLCU,NAC,3234,0,...,17,25,NaN,0,NaN,1150.94,3,5,GB14306197,GB14306199
2,1058045501,SBRZ024WK,UACU8468865,40,NGB,SOU,HLCU,NAC,3234,0,...,17,25,NaN,0,NaN,1150.94,3,5,GB14306197,GB14306199
3,1058081238,SBRZ024WK,HAMU1606105,41,YTN,SOU,HLCU,NAC,3234,0,...,17,25,NaN,0,NaN,1150.94,3,5,GB14306197,GB14306199
4,1058160730,SBRZ024WK,HLBU1837233,41,NGB,SOU,HLCU,NAC,3234,0,...,17,25,NaN,0,NaN,1150.94,3,5,GB14306197,GB14306199
5,1058214623,SBRZ024WKH,HLBU2065427,41,KOS,SOU,HLCU,FAK,4070,0,...,17,25,NaN,0,NaN,1098.05,3,4,GB14306217,GB14306216
6,1057708900,SCCL0FMFBW1MABD,CMAU6645167,41HG,CGP,SOU,CMDU,NAC,1165,0,...,17,25,NaN,0,NaN,1098.05,3,5,GB14307161,GB14307163
7,1057891840,SCCL0FMFBW1MABD,CMAU6405905,41HG,CGP,SOU,CMDU,NAC,1165,0,...,17,25,NaN,0,NaN,1098.05,3,5,GB14307161,GB14307163
8,1057891840,SCCL0FMFBW1MABD,CMAU7286441,41HG,CGP,SOU,CMDU,NAC,1165,0,...,17,25,NaN,0,NaN,1028.05,3,5,GB14307161,GB14307163
9,1057891840,SCCL0FMFBW1MABD,CMAU7519230,41HG,CGP,SOU,CMDU,NAC,1165,0,...,17,25,NaN,0,NaN,1028.05,3,4,GB14307161,GB14307163
10,1057891840,SCCL0FMFBW1MABD,SEKU4522959,41HG,CGP,SOU,CMDU,NAC,1165,0,...,17,25,NaN,0,NaN,1028.05,3,4,GB14307161,GB14307163
11,1057891840,SCCL0FMFBW1MABD,TCKU6350136,41HG,CGP,SOU,CMDU,NAC,1165,0,...,17,25,NaN,0,NaN,1028.05,3,4,GB14307161,GB14307163
12,1057891840,SCCL0FMFBW1MABD,TCLU6551082,41HG,CGP,SOU,CMDU,NAC,1165,0,...,17,25,NaN,0,NaN,1028.05,3,5,GB14307161,GB14307163
13,1057891840,SCCL0FMFBW1MABD,TCLU9124799,41HG,CGP,SOU,CMDU,NAC,1165,0,...,17,25,NaN,0,NaN,1028.05,3,5,GB14307161,GB14307163
14,1057891840,SCCL0FMFBW1MABD,TCNU3124968,41HG,CGP,SOU,CMDU,NAC,1165,0,...,17,25,NaN,0,NaN,1028.05,3,5,GB14307161,GB14307163

In [ ]:
df.dtypes

0
File Reference                                  object
Voyage Number                                   object
Container No                                    object
 Cont Type                                      object
Port of Loading                                 object
Port of Arrival                                 object
Carrier                                         object
FAK Y/N?                                        object
 Ocean Freight USD                              object
Hazardous                                       object
Reefer                                          object
 ISPS USD                                       object
 ENS Fee                                        object
Sulphur Chg                                     object
GOH Surcharge                                   object
USD Total                                       object
No of Drops                                     object
 Terminal Handling GBP                          object
 Port Security GBP                              object
 Documents GBP                                  object
 Customs Clearance GBP                          object
 Haulage GBP                                    object
DRS                                             object
 Port Inf                                       object
Energy Adjustment and Fuel Duty Recovery GBP    object
Gen Set                                         object
HAZ Surcharge                                   object
Rework                                          object
GBP Total                                       object
Gate In (Freight)                               object
Delivery Month                                  object
USD Invoice Number                              object
GBP Invoice Number                              object
dtype: object